# Project: Project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = zad1.o zad2.o zad3.o zad4name.o
LINKOBJ  = zad1.o zad2.o zad3.o zad4name.o
LIBS     = -L"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/guzki/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

zad1.o: zad1.cpp
	$(CPP) -c zad1.cpp -o zad1.o $(CXXFLAGS)

zad2.o: zad2.cpp
	$(CPP) -c zad2.cpp -o zad2.o $(CXXFLAGS)

zad3.o: zad3.cpp
	$(CPP) -c zad3.cpp -o zad3.o $(CXXFLAGS)

zad4name.o: zad4name.cpp
	$(CPP) -c zad4name.cpp -o zad4name.o $(CXXFLAGS)
